---
# on laptop anyway, edit /etc/povray/3.7/povray.ini:File_Gamma=0.85
- name: 'Render povray images from yml files'
  hosts: 'localhost'
  connection: 'local'
  vars:
    image_path: '{{ image_directory_prefix }}-{{ qual }}'
  vars_files:
  - '../vars/common.yml'
  - '../vars/{{ qual }}.yml'
  tasks:
    - name: 'Empty pics directory'
      loop:
      - 'absent'
      - 'directory'
      file:
        path: '../{{ image_path }}'
        state: '{{ item }}'
    - name: 'Output extra vars if present'
      when: extra is defined
      debug:
        var: extra
    - name: 'Loop over models'
      loop_control:
        label: '{{ item.path }}'
      when: '"/" not in item.path'
      with_filetree: '{{ pov_path }}'
      vars:
        pov_input: '/tmp/{{ pov_model }}.pov'
        pov_model: '{{ item.path }}'
        pov_output: '{{ pov_model }}.png'
      include_tasks: 'loop.yml'
...
